"""add image and thumbnail paths to users

Revision ID: 33707e594444
Revises: 2c2ec300409a
Create Date: 2026-08-20 00:25:29.373201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33707e594444'
down_revision: Union[str, Sequence[str], None] = '2c2ec300409a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'thumbnail_path')
    op.drop_column('users', 'image_path')
    # ### end Alembic commands ###
