"""add tier to users

Revision ID: 55d5309c29e5
Revises: f8a1d0c54f3f
Create Date: 2026-07-20 23:11:23.524037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '55d5309c29e5'
down_revision: Union[str, Sequence[str], None] = 'f8a1d0c54f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), server_default='hobby', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tier')
    # ### end Alembic commands ###
