"""add click tracking columns

Revision ID: d39bd0672724
Revises: 
Create Date: 2026-07-18 22:08:58.051631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39bd0672724'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('click_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('urls', sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'last_accessed_at')
    op.drop_column('urls', 'click_count')
    # ### end Alembic commands ###
