"""add expires_at to urls

Revision ID: f8a1d0c54f3f
Revises: da3727b4a414
Create Date: 2026-07-20 00:29:54.834780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a1d0c54f3f'
down_revision: Union[str, Sequence[str], None] = 'da3727b4a414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'expires_at')
    # ### end Alembic commands ###
